server:
  port: 8080

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: postgres
    password: postgreuser
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: auth-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer