server:
  port: 8084

spring:
  application:
    name: payment-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/payments_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgreuser}

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_JWKS_URI:http://localhost:8081/oauth2/jwks}
      client:
        registration:
          seller-client:
            client-id: payment-service
            client-secret: ${PAYMENT_SERVICE_CLIENT_SECRET:payment-service-secret}
            authorization-grant-type: client_credentials
            scope: seller:bankInfo
        provider:
          seller-client:
            token-uri: ${AUTH_SERVICE_TOKEN_URI:http://localhost:8081/oauth2/token}

services:
  seller:
    url: ${SELLER_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-thresholds:
        http.server.requests: 50,95,99