apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: ecommerce
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://payment-db:5432/payment_db"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  AUTH_SERVICE_JWKS_URI: "http://auth-service:8081/oauth2/jwks"
  AUTH_SERVICE_TOKEN_URI: "http://auth-service:8081/oauth2/token"
  SELLER_SERVICE_URL: "http://seller-service:8083"